name: CI

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Pack library
        run: |
          mkdir -p out/lib
          cp package.json out/
          cp LICENSE out/
          cp -r build/src/ out/lib/
          npm pack out/
      - name: Publish to npm
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          check-version: true
          package: ./out/package.json
          token: ${{ secrets.NPM_TOKEN }}
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          files: |
            *.tgz